import * as stylex from '@stylexjs/stylex';
import { colors } from '../theme.stylex';

const portrait = '@media (max-width: 850px), (orientation: portrait)';

export const styles = stylex.create({
	grid: {
		display: 'grid',
		gridTemplateColumns: { default: 'repeat(3, minmax(0, 1fr))', [portrait]: '1fr' },
		gap: 'clamp(12px, 1.25vw, 20px)',
	},
	card: {
		display: 'flex',
		minWidth: 0,
		height: { default: 'clamp(250px, 36.5vh, 374px)', [portrait]: '310px' },
		flexDirection: 'column',
		overflow: 'hidden',
		borderWidth: '4px',
		borderStyle: 'solid',
		borderRadius: '14px',
		backgroundColor: colors.surface,
	},
	currentCard: { borderColor: colors.orange },
	nextCard: { borderColor: colors.orangeDark },
	timingCard: { borderColor: colors.gold },
	cardHeader: {
		display: 'flex',
		height: 'clamp(56px, 7.1vh, 68px)',
		flex: '0 0 auto',
		alignItems: 'center',
		paddingInline: 'clamp(18px, 2vw, 30px)',
		color: 'white',
	},
	currentHeader: { backgroundColor: colors.orange },
	nextHeader: { backgroundColor: colors.orangeDark },
	timingHeader: { backgroundColor: colors.gold, color: '#171717' },
	heading: {
		margin: 0,
		fontSize: 'clamp(1.2rem, 2.2vw, 2rem)',
		fontWeight: 850,
		letterSpacing: '0.025em',
		textTransform: 'uppercase',
	},
	cardBody: {
		display: 'flex',
		minHeight: 0,
		flex: 1,
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		padding: 'clamp(16px, 2.2vh, 24px)',
		backgroundColor: colors.surface,
	},
	matchNumber: {
		fontSize: { default: 'clamp(5.4rem, 10.5vw, 8.9rem)', [portrait]: '7rem' },
		fontWeight: 900,
		fontVariationSettings: "'wdth' 92",
		lineHeight: 0.82,
		letterSpacing: '-0.045em',
	},
	matchDetail: {
		display: 'flex',
		width: '94%',
		minHeight: 'clamp(58px, 7.8vh, 76px)',
		alignItems: 'center',
		justifyContent: 'center',
		marginTop: 'auto',
		borderRadius: '10px',
	},
	fieldState: {
		backgroundColor: colors.orange,
		color: '#171717',
		fontSize: 'clamp(1.4rem, 2.5vw, 2.15rem)',
		fontWeight: 900,
		letterSpacing: '0.04em',
		textTransform: 'uppercase',
	},
	matchStartTime: {
		flexDirection: 'column',
		backgroundColor: '#3d3d3d',
		borderWidth: '2px',
		borderStyle: 'solid',
		borderColor: '#5f5f5f',
		color: '#171717',
		lineHeight: 0.95,
		textTransform: 'uppercase',
	},
	matchStartValue: { color: 'white', fontSize: 'clamp(1.65rem, 2.8vw, 2.4rem)' },
	matchStartLabel: {
		marginBottom: '4px',
		color: colors.muted,
		fontSize: 'clamp(0.72rem, 1.35vw, 1.05rem)',
		fontWeight: 850,
		letterSpacing: '0.04em',
	},
	timingBody: { alignItems: 'stretch', gap: 'clamp(8px, 1.15vh, 12px)' },
	timingRow: {
		display: 'flex',
		minHeight: 'clamp(48px, 6.4vh, 64px)',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: '12px',
		paddingBlock: '8px',
		paddingInline: 'clamp(14px, 1.8vw, 24px)',
		borderWidth: '2px',
		borderStyle: 'solid',
		borderColor: '#555',
		borderRadius: '9px',
		backgroundColor: '#353535',
	},
	timingPast: { borderColor: '#747474' },
	timingSoon: { borderColor: colors.gold, backgroundColor: colors.gold, color: '#171717' },
	timingLabel: {
		color: colors.muted,
		fontSize: 'clamp(0.8rem, 1.35vw, 1.05rem)',
		fontWeight: 800,
		letterSpacing: '0.035em',
		textTransform: 'uppercase',
	},
	timingLabelSoon: { color: '#333' },
	timingValue: { fontSize: 'clamp(1.1rem, 2vw, 1.6rem)', whiteSpace: 'nowrap' },
});
