import * as stylex from '@stylexjs/stylex';
import { colors, spacing } from '../theme.stylex';

const portrait = '@media (max-width: 850px), (orientation: portrait)';

export const styles = stylex.create({
	grid: {
		display: 'grid',
		minHeight: 0,
		height: { default: '100%', [portrait]: 'auto' },
		gridTemplateColumns: { default: 'repeat(3, minmax(0, 1fr))', [portrait]: '1fr' },
		gridColumn: '1 / -1',
		gap: { default: 0, [portrait]: spacing.lg },
	},
	card: {
		display: 'flex',
		minWidth: 0,
		height: { default: '100%', [portrait]: '23.5rem' },
		flexDirection: 'column',
		overflow: 'hidden',
		borderRadius: { default: 0, [portrait]: spacing.md },
		backgroundColor: colors.surface,
	},
	dividedCard: {
		borderInlineEndWidth: { default: '1px', [portrait]: 0 },
		borderInlineEndStyle: 'solid',
		borderInlineEndColor: colors.line,
	},
	ourMatchCard: {
		height: { default: '100%', [portrait]: 'auto' },
		gridColumn: { default: 'span 2', [portrait]: 'auto' },
	},
	ourMatchBody: {
		display: 'grid',
		minHeight: 0,
		flex: 1,
		gridTemplateColumns: { default: 'repeat(2, minmax(0, 1fr))', [portrait]: '1fr' },
	},
	ourMatchPane: {
		minHeight: { default: 0, [portrait]: '19.5rem' },
	},
	leadingPane: {
		borderInlineEndWidth: { default: '1px', [portrait]: 0 },
		borderInlineEndStyle: 'solid',
		borderInlineEndColor: colors.line,
		borderBottomWidth: { default: 0, [portrait]: '1px' },
		borderBottomStyle: 'solid',
		borderBottomColor: colors.line,
	},
	noNextCard: { gridColumn: { default: 'span 2', [portrait]: 'auto' } },
	cardBody: {
		display: 'flex',
		minHeight: 0,
		flex: 1,
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		gap: spacing.lg,
		paddingInline: spacing.lg,
		paddingBlockEnd: spacing.lg,
	},
	noNextMessage: {
		maxWidth: '26rem',
		fontSize: '3rem',
		lineHeight: 1.05,
		textAlign: 'center',
	},
	matchNumberArea: {
		display: 'flex',
		minHeight: 0,
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		padding: spacing.lg,
	},
	matchNumber: {
		fontSize: { default: 'clamp(8rem, 12vw, 12rem)', [portrait]: '7rem' },
		fontWeight: 700,
		fontVariantNumeric: 'tabular-nums',
		lineHeight: 0.82,
		letterSpacing: '-0.045em',
		whiteSpace: 'nowrap',
	},
	currentStage: {
		display: 'flex',
		maxWidth: '100%',
		flexDirection: 'column',
		fontSize: { default: 'clamp(3rem, 4vw, 4rem)', [portrait]: '3.5rem' },
		fontWeight: 700,
		lineHeight: 0.95,
		textAlign: 'center',
	},
	currentActivity: {
		maxWidth: '100%',
		fontSize: { default: 'clamp(4rem, 6.5vw, 6.5rem)', [portrait]: '4rem' },
		fontWeight: 700,
		lineHeight: 1,
		textAlign: 'center',
	},
	matchDetailSlot: {
		display: 'flex',
		width: '100%',
		minHeight: { default: '8.5rem', [portrait]: '7.5rem' },
		alignItems: 'center',
		justifyContent: 'center',
	},
	matchDetail: {
		display: 'flex',
		width: '100%',
		alignItems: 'center',
		justifyContent: 'center',
		borderRadius: spacing.sm,
	},
	matchStartTime: {
		minHeight: { default: '8.5rem', [portrait]: '7.5rem' },
		paddingInline: spacing.lg,
		backgroundColor: colors.surfaceRaised,
		containerType: 'inline-size',
	},
	matchTimeValue: {
		fontSize: 'clamp(2.5rem, 17cqw, 4.1875rem)',
		fontVariantNumeric: 'tabular-nums',
		letterSpacing: '-0.03em',
		whiteSpace: 'nowrap',
	},
	activityEndValueLong: {
		fontSize: 'clamp(2rem, 12.5cqw, 3.35rem)',
	},
	matchTimeValueWithTwoDigitHour: {
		fontSize: 'clamp(2.5rem, 14cqw, 3.5rem)',
	},
	matchTimeValueLong: {
		fontSize: 'clamp(2rem, 9cqw, 3rem)',
	},
	timingBody: {
		alignItems: 'stretch',
		gap: spacing.lg,
		padding: spacing.lg,
		containerType: 'inline-size',
	},
	matchCountdown: {
		display: 'flex',
		minHeight: 0,
		flex: 1,
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		gap: spacing.xs,
		textAlign: 'center',
	},
	matchCountdownLabel: {
		color: colors.muted,
		fontSize: { default: '2.5rem', [portrait]: '2rem' },
		fontWeight: 700,
		letterSpacing: '0.035em',
	},
	matchCountdownValue: {
		fontSize: 'clamp(3.5rem, 26cqw, 7rem)',
		fontVariantNumeric: 'tabular-nums',
		lineHeight: 1,
		letterSpacing: '-0.03em',
		whiteSpace: 'nowrap',
	},
	matchCountdownValueLong: {
		fontSize: 'clamp(2.5rem, 16cqw, 6rem)',
	},
	matchCountdownValueWithHours: {
		fontSize: 'clamp(2.5rem, 21.5cqw, 6rem)',
	},
	matchCountdownValueWithSeconds: {
		fontSize: 'clamp(2.5rem, 19.5cqw, 6rem)',
	},
	timingStatuses: {
		display: 'flex',
		width: '100%',
		minHeight: { default: '8.5rem', [portrait]: '7.5rem' },
		flexDirection: 'column',
		justifyContent: 'flex-end',
		gap: spacing.sm,
	},
	timingRow: {
		display: 'flex',
		minHeight: { default: '4rem', [portrait]: '3.5rem' },
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: spacing.md,
		paddingBlock: spacing.sm,
		paddingInline: spacing.lg,
		borderWidth: '2px',
		borderStyle: 'solid',
		borderColor: colors.line,
		borderRadius: spacing.sm,
		backgroundColor: colors.surfaceRaised,
	},
	timingLabel: {
		color: colors.muted,
		fontSize: '1.5rem',
		fontWeight: 700,
		letterSpacing: '0.035em',
		whiteSpace: 'nowrap',
	},
	timingValue: {
		fontSize: '1.75rem',
		fontVariantNumeric: 'tabular-nums',
		whiteSpace: 'nowrap',
	},
});
