name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build and test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1.19.0
        with:
          cache: true
      - run: vp check
      - run: vp exec knip
      - run: vp build
        env:
          VITE_CONVEX_URL: https://stoic-mouse-746.convex.cloud
